/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import okhttp3.*;
import org.json.JSONObject;
import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {


        //insert the copied code below this line



        System.out.println(new JSONObject(response.body().string()).toString(2));
    }

}
