/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;

import java.io.IOException;
import java.util.Arrays;
import java.util.stream.Collectors;

public class App {

    public static void main(String[] args) throws IOException {


        //insert the copied code below this line


        printResponse(response);
    }

    private static void printResponse(Response response) throws IOException {
        System.out.println(Arrays.stream(response.body().string().split(""))
                .map(ch -> {
                    if ("{".equals(ch)
                    ) {
                        ch = ch.replace("{", "\n{");
                    }
                    if (",".equals(ch)
                    ) {
                        ch = ch.replace(",", ",\n");
                    }
                    return ch;
                })
                .collect(Collectors.joining()));
    }
}
