/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kyriba;

import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;

import java.io.IOException;
import java.util.Arrays;
import java.util.stream.Collectors;

public class App {

    public static void main(String[] args) throws IOException {
        OkHttpClient client = new OkHttpClient().newBuilder()
                .build();
        Request request = new Request.Builder()
                .url("https://demo.kyriba.com/gateway/api/v1/accounts?filter=code != null")
                .method("GET", null)
                .addHeader("Authorization", "Bearer 66edf52f-38eb-42ca-b557-c756220bea8c")
                .build();
        Response response = client.newCall(request).execute();


        printResponse(response);
    }

    private static void printResponse(Response response) throws IOException {
        System.out.println(Arrays.stream(response.body().string().split(""))
                .map(ch -> {
                    if ("{".equals(ch)
                    ) {
                        ch = ch.replace("{", "\n{");
                    }
                    if (",".equals(ch)
                    ) {
                        ch = ch.replace(",", ",\n");
                    }
                    return ch;
                })
                .collect(Collectors.joining()));
    }
}
